---

- name: Setup VCC Research Base
  hosts: general_server:dev_server:localhost
  remote_user: root
  become: yes
  roles:
    - ANXS.timezone
    - ANXS.build-essential
    - ANXS.git
    - ANXS.fail2ban
    - ANXS.logwatch
    - geerlingguy.postfix
    - avanov.pyenv
    - andrewrothstein.anaconda
    - ANXS.postgresql
